---
- name: Configurar SSHD de forma segura
  hosts: MV
  become: true

  tasks:
    - name: Asegurar que ssh está instalado
      apt:
        name: openssh-server
        state: present
        update_cache: yes

    - name: Configurar PermitRootLogin no y PasswordAuthentication no en sshd_config
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?{{ item.key }}'
        line: '{{ item.key }} {{ item.value }}'
        state: present
        backup: yes
      loop:
        - { key: 'PermitRootLogin', value: 'no' }
        - { key: 'PasswordAuthentication', value: 'no' }

    - name: Reiniciar servicio sshd para aplicar cambios
      systemd:
        name: ssh
        state: restarted
        enabled: yes
