FROM docker.io/library/debian:stable-slim
RUN apt-get update && \
    apt-get install -y nginx && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
VOLUME /var/www/html
VOLUME /etc/nginx/nginx.conf
EXPOSE 80
CMD ["/bin/nginx", "-g", "daemon off;"]
