FROM debian:stable-slim

RUN apt-get update -y && apt-get upgrade -y && apt-get install -y nginx

COPY conf/nginx.conf /etc/nginx/nginx.conf

VOLUME [ "/usr/share/nginx/html" ]

CMD [ "nginx", "-g", "daemon off;" ]
