
#Se permite acceder a WordPress desde fuera del cluster 
apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  type: NodePort   #Se ecpone el sitio WordPress a través de un puerto del nodo 
  selector:        #Se redirige el táfico a los pods 
    app: wordpress
    tier: frontend
  ports:
    - protocol: TCP
      port: 80    #Puerto dentro de cluster que escucha el trafico HTTP
---
#Se solicita 1GiB de almacenamiento persistente para guardar wl contenido de WordPress 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
#Se deifine un Deployment lalmado wordpress que mantiene activo un pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:      #Etiquetas del pod
      app: wordpress
      tier: frontend
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: wordpress:latest    #  Se usa la imagen oficial de WordPress
        name: wordpress
#Se usa secret para configurar la conexion con la base de datos
        env:
        - name: WORDPRESS_DB_HOST   #Nombre de Service que apunta a MariaDB
          value: wordpress-mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: username
        - name: WORDPRESS_DB_NAME
          value: wordpress
#Se monta el puerto 80 y monta el volumen persistente en vat/www/html
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
#Se usa el PVC que se creó paa almacenar los datos del sitio 
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
