---
- name: Configuration of firewall
  hosts: myhosts
  become: yes 
  tasks:
      - name: Add sources for having nftables
        ansible.builtin.copy:
          src: conf.d/repositories.list
          dest: /etc/apt/sources.list.d

      - name: Reload repositories
        apt:
          upgrade: yes
          update_cache: yes
    
      - name: Install nftables
        ansible.builtin.apt:
          name: nftables
          state: present
      - name: Configure nftables
        ansible.builtin.copy:
          src: conf.d/nftables.conf
          dest: /etc/nftables.conf
      
      - name: start service
        ansible.builtin.systemd_service:
          name: nftables.service
          enabled: yes
          state: restarted
...