---
    - name: 
      ansible.builtin.blockinfile:
        name: /etc/ssh/sshd_config
        block: |
          Port 22
          PermitRootLogin no
          PasswordAuthentication no
          PubkeyAuthentication yes
          X11Forwarding no
        marker: "# {mark} sshd configuration"
        insertafter: EOF
...
